version: "3.9"
services:
  nginx_simple_rest:
    container_name: nginx_simple_rest
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    links:
      - php_simple_rest
  php_simple_rest:
    container_name: php_simple_rest
    image: php:7.4-fpm
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
